builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

brews:
  - github:
      owner: fibbery
      name: homebrew-tap
    commit_author:
      name: fibbery
      email: jiangnenghua1992@gmail.com
    folder: Formula
    install: |
      bin.install "csv2keychain"
