language: go

addons:
  apt:
    packages:
      - rpm
      - snapd
env:
  - PATH=/snap/bin:$PATH GO111MODULE=on
install:
  - sudo snap install snapcraft --classic
deploy:
  - provider: script
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
